### ISSUE TITLE
Right click action triggers Click action

### ISSUE THREAD

**Issue by ClotildeToullec** [TelescopeSt/TelescopeRoassal3#17]
When a click and a right-click interactions are defined, a right click triggers both interactions.

Example below:
- A click on a node expands its children.
- A right click on a node should just hide the node, but it also expands its children.

![Telescope - Right click bug](https://user-images.githubusercontent.com/39184695/99667026-0f82d880-2a6c-11eb-90da-1d6bfec1ad8f.gif)

**Comment by akevalion** [comment]
Hi @ClotildeToullec Thank you very much for this feed back.

I have fixed this, can you tell me if this is the thing you expected?
```Smalltalk
visualization := TLVisualization new.
visualization addNodeFromEntity: 1.
visualization nodeLabel: #asString.
visualization layout: TLTreeLayout new useOutgoingLinks.

visualization addInteraction: 
	(TLExpandCollapseNodesAction property: [:n | { n * 10. n * 10 + 11} ]) onClick.
visualization addInteraction: (TLHideAction hide: #yourself) onRightClick.
visualization open
```

**Comment by ClotildeToullec** [comment]
Yes, it seems perfect, thank you !
